[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "lombik"
version = "2.0.0"
description = "Flask scaffold engine"
authors = [
    { name="David Plajner" }
]
readme = "README.md"

dependencies = [
    "Flask",
    "Flask-SQLAlchemy",
    "Flask-Migrate",
    "Flask-WTF",
    "Flask-Session",
    "Flask-Caching",
    "Flask-Limiter",
    "python-dotenv",
    "click",
    "SQLAlchemy",
    "Werkzeug"
]

[project.scripts]
lombik = "lombik.cli:cli"
